<?xml version="1.0"?>
<package format="3">
  <name>rover_navigation</name>
  <version>0.0.0</version>
  <description>Simple waypoint navigation for the challenge rover</description>
  <maintainer email="kabir-arora@todo.todo">kabir-arora</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
